### ISSUE TITLE
missing `silicate::` in new_as.mesh3d.R

### ISSUE THREAD

**Issue by gsapijaszko** [hypertidy/anglr#161]
There are few places where call for `silicate::` is missing, like:

```r
as.mesh3d.SC0 <- function(x, ...) {
  v <- sc_vertex(x)
```
instead of 
```
as.mesh3d.SC0 <- function(x, ...) {
  v <- silicate::sc_vertex(x)
```

PR on the way.

**Comment by mdsumner** [comment]
appreciated!   

this has been backgrounded a while now but I've done quite a lot of work in the background that will be able to improve things here

**Comment by gsapijaszko** [comment]
Closing the issue, it was fixed. Thank you @mdsumner :)

**Comment by mdsumner** [comment]
also, I'm going to shift to the main branch  - and hopefully delete master sometime soon
