### ISSUE TITLE
flight_tracks example

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/anglr#45]
@kent37 thanks for the data, I've included it within the package `silicate`, which I hope is ok?  There it is in `PATH` form, which you can create from an `sf` with `silicate::PATH( )`. There's still another step into `anglr` form while I figure out the best way forward. 

If you are feeling brave, try installing `anglr`, there is one other Github package `silicate`, and `rgl` and a few other packages are required from CRAN. You'll likely need a pretty recent version of R, I'm using 3.4.1. 

The `rgl.clear()` at the start of the plot and `rglwidget()` is a bit of overkill, but it's necessary for me working on RStudio Server. 

This project is still very early and raw, but it's looking promising. Let me know how it goes, good or bad - it's helpful to know any feedback. We can put other features in the scene easily enough, including polygons with topography relief and so forth, but all of that takes a bit of knowledge of the structures at the moment. 

```R
## devtools::install_github("hypertidy/silicate")
## devtools::install_github("hypertidy/anglr")

library(anglr)
library(rgl)
data("flight_tracks", package = "silicate")
## convert to topological graph
aa <- anglr(flight_tracks)

rgl.clear()
## sets up a basic plot, with a colour for each feature
##  (M is ignored, but it's in the model - see aa$v)
plot(aa)
## this is a hack, z-metres in lon-lat
## play with the third value by orders of magnitude
## but re-run the rgl.clear to rglwidget funs 
## completely start again if needed
aspect3d(1, 1, 0.0001)
## this call is not needed unless you are on RSTudio Server, or have no OpenGL rgl device
rglwidget()
```

Finally, a specific thing if you can let me know, are you able to rotate the scene as well as zoom in and out? I'm having troubles, I don't understand the details of rglwidget yet. :)

**Comment by kent37** [comment]
See my comments to https://github.com/hypertidy/silicate/commit/4b2c057272b0eded5fe23d32865598cefef3540c.

Thanks for the code sample, I will try it.

**Comment by mdsumner** [comment]
I doubt this ever worked before except on my machine, but the latest versions of silicate an anglr are much more robust. This example should work. There's no need for `copy_down` because the source already has Z (and M). 

```R
## devtools::install_github("hypertidy/silicate")
## devtools::install_github("hypertidy/anglr")

library(anglr)
library(silicate)

data("flight_tracks", package = "silicate")
## sets up a basic plot, with a colour for each feature
##  (M is ignored, but it's in the model - see flight_tracks$vertex)
plot3d(flight_tracks)
rgl::aspect3d(1, 1, 0.1)
## this call is not needed unless you are on RSTudio Server, or have no OpenGL rgl device
rgl::rglwidget()

```
