### ISSUE TITLE
How to plot a linemesh?

### ISSUE THREAD

**Issue by MilesMcBain** [hypertidy/anglr#52]
I downloaded a shapefile which `sf` read in as a MULTILINESTRING. `anglr` converts this to a `linemesh`, which I don't understand how to draw in 3D. What am I missing?

Edit: I've committed the shape file and related code in `alexander_clark_park` in our vr_vs_sp repo.

**Comment by mdsumner** [comment]
You can plot it directly (via rgl)

```R
library(anglr)
library(sf)
mls <- st_cast(read_sf(system.file("shape/nc.shp", package="sf")), 
              "MULTILINESTRING")

lmesh <- anglr(mls)
a <- plot(lmesh) ## or plot(globe(lmesh))

## ... I have to run rgl::rglwidget() in RSTudio server (and reset with rgl::rgl.clear()
```

It's a bit whack, but lmesh has  `vertex_` and `segment_` on the vertex table, to link up through lXv and l. 

That plot method returns 'a' above which is the rgl array structures, literally `v` the 3D geometry and `it` the 2-index segments, `rgl` doesn't have a formal type for "lines" so I left it at that ('it' means "index for triangles" so I should have changed that). 

Does that help? I have to think really hard to revisit what plot(lmesh) does here, but it's the usual join-ramp chicanery - and I've been scheming on better ways for this :)

**Comment by mdsumner** [comment]
Ah, forget the above. 

I thought it was the units of the space, but it's something else. We also need to "copy down" the elevation onto the vertices, this is a good example - but might take me a bit.

**Comment by mdsumner** [comment]
Here it is finally, I use the join links to copy ELEVATION from the features down to the vertices. 

There's problems with some of my segments, so that's an `anglr` bug that new work in silicate will fix soon. 

```R
library(anglr)
library(sf)

mls <- read_sf("../vr_vs_sp/alexander_clark_park/QSC_Extracted_Data_20171212_140035727000-20064/Contours_1_metre.shp")
## transform to a local projection in metres since
range(mls$ELEVATION)
# [1] 1 10
## could build proj string from st_centroid
pmls <- st_transform(mls, "+proj=laea +lon_0=153 +lat_0=-27 +datum=WGS84")
lmesh <- anglr(pmls)
## currently lmesh$v$z_ is missing, assumed 0 later
## so we need to "copy down"
## (this could be a function in sf)
## (note that my join trail from anglr() for lines is a real mess but nvm ...)
library(dplyr)
lmesh$v <- lmesh$v %>% inner_join(lmesh$l, "segment_") %>% 
  inner_join(lmesh$o %>% dplyr::select(object_, ELEVATION)) %>% 
  transmute(segment_, vertex_, x_, y_, z_ = ELEVATION)
## now we should be good
plot(lmesh)
rgl::aspect3d(1, 1, 0.2)

```

There's also a nice example here where I took this a bit further to "fuse" cadastral parcels in with contours like this, so we end up with a surface mesh of two sources - and since then it's been many months sorting out other details!  Progress is good though!  

https://github.com/hypertidy/anglr/issues/16#issuecomment-243743396

**Comment by mdsumner** [comment]
This makes me think I'm doing something totally wrong with ELEVATION, here's a rough stab at interpolating between the contours, it's definitely worthy of finding a better solution ...


```R


library(anglr)
library(sf)

mls <- read_sf("../vr_vs_sp/alexander_clark_park/QSC_Extracted_Data_20171212_140035727000-20064/Contours_1_metre.shp")
smls <- st_simplify(st_transform(mls, "+proj=laea +lon_0=153 +lat_0=-27 +datum=WGS84"), dTolerance = 1)
library(raster)
bb <- st_as_sf(as(extent(st_bbox(smls)[c(1, 3, 2, 4)]), "SpatialPolygons"))
smls <- smls[, "ELEVATION"]
st_crs(bb) <- st_crs(smls)
bb$ELEVATION <- 10
smls <- rbind(smls, bb)
smesh <- anglr(smls)
library(dplyr)
smesh$v <- smesh$v %>% inner_join(smesh$l, "segment_") %>% 
  inner_join(smesh$o %>% dplyr::select(object_, ELEVATION)) %>% 
  transmute(segment_, vertex_, x_, y_, z_ = ELEVATION)
## now we should be good
a <- plot(smesh)

library(RTriangle)
tri <- RTriangle::triangulate(RTriangle::pslg(P = t(a$v[1:2, ]), S = t(a$it), PA = t(a$v[3, , drop = FALSE])), a = 8722)

## now we have something else
rgl::triangles3d(cbind(tri$P, tri$PA)[t(tri$T), ], col = "white")
rgl::aspect3d(1, 1, .2)

```

**Comment by mdsumner** [comment]
Man I'm messing this up so badly, I haven't figured out where the code goes wrong in R - but I made a plot in Eonfusion to make sure I have a clear target of what this *should* look like 

![image](https://user-images.githubusercontent.com/4107631/33920832-48765d24-e014-11e7-81ba-b6043ed59648.png)

**Comment by MilesMcBain** [comment]
Oh that looks cool! As does the one in #16. I think what's happening is the order of the lines is changing somewhere in the conversion process so the ELEVATIONS are getting mapping to the wrong contour.

I had code that looked like this:
```
nc <- read_sf("./alexander_clark_park/QSC_Extracted_Data_20171212_140035727000-20064/Contours_1_metre.shp")
p_mesh <- anglr(nc, max_area = 0.008)

vertexes <- reduce(list(p_mesh$v, p_mesh$lXv, p_mesh$l, p_mesh$o), left_join)
vertex_dupes <- which(duplicated(vertexes$vertex_))
p_mesh$v$z_ <- vertexes$ELEVATION[-vertex_dupes]
```
And the order of my `p_mesh$v$z_` is not the sames as `smesh$v$z_`

I found the process of 'copying down' elevation simple enough. The titdy form helps a lot in this regard.

**Comment by mdsumner** [comment]
We now have

```R
library(anglr)
library(sf)

mls <- read_sf("../vr_vs_sp/alexander_clark_park/QSC_Extracted_Data_20171212_140035727000-20064/Contours_1_metre.shp")
smls <- st_simplify(st_transform(mls, "+proj=laea +lon_0=153 +lat_0=-27 +datum=WGS84"), dTolerance = 1)

mesh <- copy_down(silicate::SC(smls), smls$ELEVATION)
plot3d(mesh)
##rgl::aspect3d(1, 1, .5); rgl::rglwidget()
```

**Comment by mdsumner** [comment]
For interpolating a surface we can ignore the lines completely and build a triangulation on the points only. 

```R
library(anglr)
library(sf)

mls <- read_sf("../vr_vs_sp/alexander_clark_park/QSC_Extracted_Data_20171212_140035727000-20064/Contours_1_metre.shp")
prj <- "+proj=laea +lon_0=153 +lat_0=-27 +datum=WGS84"
mls <- st_transform(mls, prj)

zmesh <- copy_down(silicate::SC(mls), mls$ELEVATION)
xyz <- as.matrix(zmesh$vertex[c("x_", "y_", "z_")])
## can use geometry, RTriangle, sf, deldir, or others
tri <- geometry::delaunayn(xyz[,1:2])
rgl.triangles(xyz[t(tri), ])
rglwidget()
```

There's no anglr-ish way to do this atm, but there should be. I'll also figure out a segment-constrained way to do it a t some point.

**Comment by mdsumner** [comment]
Back in action (are you patient ...)

```R
library(anglr)
library(sf)

mls <- read_sf("../vr_vs_sp/alexander_clark_park/QSC_Extracted_Data_20171212_140035727000-20064/Contours_1_metre.shp")
## the cast is require else we have a mix of LINESTRING and MULTILINESTRING
smls <- st_cast(st_simplify(st_transform(mls, "+proj=laea +lon_0=153 +lat_0=-27 +datum=WGS84"), dTolerance = 1))

## a constant value is copied straight on to vertices
mesh <- copy_down(silicate::SC(mls), "ELEVATION")
rglmesh <- plot3d(mesh)
rgl::aspect3d(1, 1, .5); rgl::rglwidget()

```

a weird thing is that "rglmesh" is now class "segment3d", "shape3d" - which doesn't exist in rgl, but should IMO. I have an internal `shade3d.segment3d` which will plot it, but it's "vb" and "is" for transpose vertices and segment index. 

I forget where I got to with triangulating but I'll dig it up soonish.
