### ISSUE TITLE
interactive demos via github

### ISSUE THREAD

**Issue by mpadge** [hypertidy/anglr#70]
@mdsumner you can generate an interactive (`rgl` or whatever) plot via github with the following steps:

1.  Copy the contents of `tempdir()` to a new github repo,
2. Switch on github pages for that repo (to Master branch)
3. Put links in `anglr` readme

They still won't display in interactive mode on your readme, but at least that will maintain github stuff within github, and with a generally nicer aesthetic than `rpubs`. Example `tempdir()` contents from a `mapview` call are [here](https://github.com/ATFutures/accra-flows-ped-to-bus), with the link going straight to the interactive demo. This workflow also means that you can edit the demos, the impossibility of which via `rpubs` is frankly an utter killer.

**Comment by mdsumner** [comment]
oh nice, thanks!

**Comment by mdsumner** [comment]
Done, finally, thanks muchly!
